import rclpy
from rclpy.node import Node

import numpy as np                         # Matrix operations
from rclpy.qos import QoSProfile, ReliabilityPolicy

from irobot_create_msgs.msg import WheelVels   # Wheel velocity measurements
from nav_msgs.msg import Odometry              # Robot odometry
from geometry_msgs.msg import Twist            # Velocity commands

import math


# ---------------------------------------------------------
# QoS configuration
# ---------------------------------------------------------

# BEST_EFFORT is suitable for high-frequency sensor data.
# A small number of missed messages is acceptable because
# newer measurements quickly replace older ones.
qos = QoSProfile(
    reliability=ReliabilityPolicy.BEST_EFFORT,
    depth=10
)


class CompVel(Node):
    """
    Velocity compensation controller.

    This node receives desired velocity commands and applies
    a compensation model to account for the difference between:

        - commanded velocity
        - actual measured velocity

    The controller uses:
        - desired velocity commands
        - wheel velocity measurements
        - odometry angular velocity

    It produces compensated commands published to:

        /robot_2/cmd_vel
    """

    def __init__(self):

        # Initialise ROS2 node.
        super().__init__('comp_vel')


        # ---------------------------------------------------------
        # Robot parameters
        # ---------------------------------------------------------

        # Wheel radius (metres).
        #
        # Used to convert wheel angular velocity into
        # linear wheel velocity.
        self.r = 0.03575


        # ---------------------------------------------------------
        # ROS publishers and subscribers
        # ---------------------------------------------------------

        # Publish compensated velocity commands.
        self.cmd_pub = self.create_publisher(
            Twist,
            '/robot_2/cmd_vel',
            10
        )


        # Subscribe to desired velocity commands.
        #
        # This is the command generated by another controller
        # (for example trajectory or wall following).
        self.cmd_sub = self.create_subscription(
            Twist,
            '/robot_2/cmd_vel_des',
            self.des_vel,
            10
        )


        # Subscribe to odometry velocity estimate.
        self.create_subscription(
            Odometry,
            '/robot_2/odom',
            self.odom_cb,
            qos
        )


        # Subscribe to measured wheel velocities.
        self.create_subscription(
            WheelVels,
            '/robot_2/wheel_vels',
            self.wheelvel_cb,
            qos
        )


        # ---------------------------------------------------------
        # Controller parameters
        # ---------------------------------------------------------

        # Gains used for the nonlinear error correction.
        self.declare_parameter("l_v", 1)
        self.declare_parameter("k_v", 2)

        self.declare_parameter("l_w", 1)
        self.declare_parameter("k_w", 2)


        self.l_v = self.get_parameter("l_v").value
        self.k_v = self.get_parameter("k_v").value

        self.l_w = self.get_parameter("l_w").value
        self.k_w = self.get_parameter("k_w").value


        # ---------------------------------------------------------
        # Velocity states
        # ---------------------------------------------------------

        # Current desired linear and angular velocities.
        self.v = 0.0
        self.w = 0.0


        # Measured robot velocities.
        self.v_r = 0.0
        self.w_r = 0.0


        # Previous desired velocities.
        #
        # Required to calculate acceleration terms.
        self.v_prev = 0.0
        self.w_prev = 0.0


        # Run compensation controller at 20 Hz.
        self.timer = self.create_timer(
            0.05,
            self.timer_callback
        )


    # ---------------------------------------------------------
    # Desired velocity callback
    # ---------------------------------------------------------

    def des_vel(self, msg):
        """
        Store the newest desired velocity command.

        Previous commands are saved because the controller
        requires the velocity derivative.
        """

        self.v_prev = self.v
        self.w_prev = self.w

        self.v = msg.linear.x
        self.w = msg.angular.z



    # ---------------------------------------------------------
    # Odometry callback
    # ---------------------------------------------------------

    def odom_cb(self, msg):
        """
        Store measured angular velocity from odometry.
        """

        self.w_r = (
            msg.twist.twist.angular.z
        )



    # ---------------------------------------------------------
    # Wheel velocity callback
    # ---------------------------------------------------------

    def wheelvel_cb(self, msg):
        """
        Convert wheel angular velocities into robot linear
        velocity using differential-drive kinematics.
        """

        r = self.r


        # Convert wheel angular velocities
        # into linear wheel velocities.
        vL = r * msg.velocity_left
        vR = r * msg.velocity_right


        # Robot forward velocity is the average
        # of the two wheel velocities.
        self.v_r = (
            vR + vL
        ) / 2.0



    # ---------------------------------------------------------
    # Compensation controller
    # ---------------------------------------------------------

    def compensating_controller(self):
        """
        Calculate compensated velocity commands.

        The controller combines:

            1. Velocity tracking error correction
            2. Desired velocity acceleration
            3. Robot dynamic compensation model

        The resulting output is a corrected velocity command
        that attempts to make the real robot motion match the
        desired motion.
        """


        # -----------------------------------------------------
        # Learned/identified robot model parameters
        # -----------------------------------------------------

        # These parameters represent the robot's dynamic model.
        theta1 = 0.0684
        theta2 = 0.2431
        theta3 = -0.0170
        theta4 = 0.9773
        theta5 = -0.0593
        theta6 = 0.8373


        # Controller gains.
        l_v = self.l_v
        l_w = self.l_w

        k_v = self.k_v
        k_w = self.k_w


        # Current and previous desired velocities.
        v_prev = self.v_prev
        w_prev = self.w_prev

        v = self.v
        w = self.w


        # Measured velocities.
        v_r = self.v_r
        w_r = self.w_r



        # -----------------------------------------------------
        # Velocity error correction
        # -----------------------------------------------------

        # Difference between commanded and measured motion.
        v_err = v_prev - v_r
        w_err = w_prev - w_r


        # Nonlinear correction term.
        #
        # tanh limits the maximum correction magnitude,
        # preventing very large control outputs.
        v_hol = (
            l_v *
            math.tanh(
                (k_v / l_v) * v_err
            )
        )

        w_hol = (
            l_w *
            math.tanh(
                (k_w / l_w) * w_err
            )
        )



        # -----------------------------------------------------
        # Desired acceleration
        # -----------------------------------------------------

        # Controller update period is 0.05 seconds.
        dv = (
            v - v_prev
        ) / 0.05

        dw = (
            w - w_prev
        ) / 0.05



        # -----------------------------------------------------
        # Dynamic compensation model
        # -----------------------------------------------------

        # H represents the inertial component.
        H = np.array([
            [theta1, 0],
            [0, theta2]
        ])


        # C represents coupling between linear
        # and angular motion.
        C = np.array([
            [0, -theta3*w],
            [theta3*w, 0]
        ])


        # F represents friction and velocity-dependent effects.
        F = np.array([
            [theta4, 0],
            [0, theta6 + (theta5-theta3)*v]
        ])


        # Tracking correction term.
        T = np.array([
            [v_hol],
            [w_hol]
        ])


        # Desired acceleration vector.
        DU = np.array([
            [dv],
            [dw]
        ])


        # Desired velocity vector.
        U = np.array([
            [v],
            [w]
        ])



        # Final compensated control command:
        #
        # U_c =
        #     H(acceleration + correction)
        #     + C(velocity)
        #     + F(velocity)
        #
        U_c = (
            H @ (DU + T)
            +
            C @ U
            +
            F @ U
        )


        return U_c



    # ---------------------------------------------------------
    # Main controller loop
    # ---------------------------------------------------------

    def timer_callback(self):
        """
        Periodically compute and publish compensated velocity.
        """

        # Calculate corrected command.
        U = self.compensating_controller()


        # Convert matrix output into ROS Twist message.
        msg = Twist()

        msg.linear.x = U[0, 0]
        msg.angular.z = U[1, 0]


        # Publish compensated velocity.
        self.cmd_pub.publish(msg)



def main(args=None):
    """
    Main program entry point.
    """

    # Initialise ROS2.
    rclpy.init(args=args)


    # Create compensation controller node.
    node = CompVel()


    try:

        # Keep node running.
        rclpy.spin(node)


    except KeyboardInterrupt:
        pass



    # ---------------------------------------------------------
    # Stop robot before shutdown
    # ---------------------------------------------------------

    stop = Twist()

    node.cmd_pub.publish(stop)


    # Clean up ROS resources.
    node.destroy_node()

    rclpy.shutdown()



# Program entry point.
if __name__ == '__main__':
    main()
